######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 26 20:44:37 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MainWindow.cpp rc.c canvas.cpp
SOURCES += canvas.cpp Main.cpp MainWindow.cpp rc.c
