######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 29 19:19:20 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MainWindow.cpp rc.c canvas.cpp
SOURCES += canvas.cpp Main.cpp MainWindow.cpp rc.c
